
export interface IStop {
  id?: number,
  addresName?: string,
  addres?: string,
  comunaId?: number,
  phone?: string,
  notes?: string,
  photos?: string,
  status?: string,
  buyOrder?: string,
  sellId?: number,
  driverId?: number,
  rateId?: number,
  lat?: number,
  lng?: number,
  fragile?: boolean,
  devolution?: boolean,
  createAt?: Date,
  updateAt?: Date,
}